server:
 port: 8080
spring:
 datasource:
   username: root
   password: Qwer2Qwer
   url:
        jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
        eSSL=false&allowPublicKeyRetrieval=true
   driver-class-name: com.mysql.cj.jdbc.Driver

     #  com.mysql.cj.jdbc.Driver

     # net.sf.log4jdbc.sql.jdbcapi.DriverSpy

   #        jdbc:log4jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
   #        eSSL=false&allowPublicKeyRetrieval=true



 jpa:
  properties:
   hibernate:
   dialect: org.hibernate.dialect.MySQL5Dialect
   ddl-auto: create-update
   show-sql: true


  generate-ddl: true
  show-sql: true

---

indexing-settings:
  sites:
    - url: https://nikoartgallery.com/
      name: Galerey Nikola
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://et-cetera.ru/mobile/
      name: Theatre



---
indexing-agent:
         userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6
         referrer: http://www.google.com


---
logging:
  file:
    name: Log\logging


---

my-labels:
   indexingStarted: Индексация уже запущена
   indexingNotStarted: Индексация еще не запущена
   indexingStopedUser: Индексация остановлена пользователем
   thisPageOutSite: Данная страница находится за пределами сайтов, указанных в конфигурационном файле



